version: 2
jobs:
  build:
    machine:
      - image: circleci/classic:latest
    environment:
      - RUBIES: "ruby-2.4.2 ruby-2.2.7 ruby-2.1.9 ruby-2.0.0 ruby-1.9.3 jruby-1.7.22 jruby-9.0.5.0 jruby-9.1.13.0"
    steps:
      - run: |
          set -e
          for i in $RUBIES;
          do
            rvm install $i;
            rvm use $i;
            if [[ $i == jruby* ]]; then
              gem install jruby-openssl; # required by bundler, no effect on Ruby MRI
            fi
            gem install bundler;
            bundle install;
            mv Gemfile.lock "Gemfile.lock.$i"
          done
      - run: |
          set -e
          for i in $RUBIES;
          do
            rvm use $i;
            cp "Gemfile.lock.$i" Gemfile.lock;
            bundle exec rspec spec;
          done
